<a href="https://colab.research.google.com/github/a00101/datascience101/blob/main/03.Linear_regression-01.Linear_regression" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

지도학습에는 regression와 classification이 있음. 

이번에는 regression 중 **linear regression**을 다룸

**2. 가설 (hypothesis) 수립**

y = Wx+b 형식이라고 가정

**3. Cost function**

오차를 modeling 하는 수식

 = Cost function (비용 함수) = loss function (손실 함수) = error function (오차 함수) = objective function (목적 함수)


**3. Optimizer - Gradient descent**

Optimizer 알고리즘 (=최적화 알고리즘)

기본적인 optimizer 알고리즘 중 하나인 gradient descent.



In [6]:
# Step1 - 기본 세팅
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [7]:
# Step2 - 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])


In [8]:
# Step3 - 가중치와 편향 초기화

W = torch.zeros(1, requires_grad=True)  # 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수(requires_grad)임을 명시함
print(W) # 가중치 출력
b = torch.zeros(1, requires_grad=True) # 편향 b를 0으로 초기화
print(b) # 편향 출력

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [9]:
# Step4 - 가설 세우기
hypothesis = x_train * W + b # hypo = x*W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
# Step5 - 비용 함수 선언하기
cost = torch.mean((hypothesis - y_train) ** 2) # 편차의 제곱으로 cost 를 정의
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [11]:
# Step6 - 경사 하강법 구현하기
optimizer = optim.SGD([W, b], lr=0.01) # lr = learning rate
optimizer.zero_grad() # gradient 를 0으로 초기화
cost.backward() # 비용 함수를 미분하여 gradient 계산
optimizer.step() # W와 b를 업데이트

In [13]:
# Step7 - 반복시행

nb_epochs = 10000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 1000 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/10000 W: 1.971, b: 0.066 Cost: 0.000627
Epoch 1000/10000 W: 1.997, b: 0.006 Cost: 0.000005
Epoch 2000/10000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 3000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 4000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 5000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 6000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 7000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 8000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 9000/10000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 10000/10000 W: 2.000, b: 0.000 Cost: 0.000000
